import { Geist, Geist_Mono } from "next/font/google";
import { Open_Sans } from "next/font/google";
import "./globals.css";
import Sidebar from "./components/Sidebar";
import Header from "./components/Header";

const openSans = Open_Sans({
  variable: "--font-open-sans",
  subsets: ["latin"],
});
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${openSans.variable}`}>
        <script
          defer
          src="https://cloud.umami.is/script.js"
          data-website-id="e4f61452-5df3-4dd5-bbb1-54586e6d9dbe"
        ></script>
        <Header />
        <Sidebar />
        <div className="pt-12 md:pt-0 md:ml-64">{children}</div>
      </body>
    </html>
  );
}
